query ($username: String!, $from: DateTime!, $to: DateTime!) {
	user(login: $username) {
		contributionsCollection(from: $from, to: $to) {
			contributionCalendar {
				totalContributions
				weeks {
					contributionDays {
						date
						contributionCount
						color
					}
				}
			}
		}
	}
}
